# https://taskfile.dev

version: '3'

vars:
  EXENAME: distributed-rate-limiter.exe
  REDIS_ADDR: 127.0.0.1:6379
  REDIS_USER: default
  REDIS_PASS: mypassword
  PERIOD: 60
  REQ_LIMIT: 2
  REDIS: false
  ALGO: fixed_window
  PORT: 12600
  MODE: "dev"

tasks:
  build:
    cmds:
      - go build -o bin/{{.EXENAME}}
    silent: true

  run:
    deps: [build]
    cmds:
      - ./bin/{{.EXENAME}} --redisaddr {{.REDIS_ADDR}} --redisuser {{.REDIS_USER}} --redispassword {{.REDIS_PASS}} --period {{.PERIOD}} --reqlimit {{.REQ_LIMIT}} --noredisallowed {{.REDIS}} --default_limit_algorithm {{.ALGO}} --port {{.PORT}} --mode {{.MODE}}

  help:
    deps: [build]
    cmds:
      - ./bin/{{.EXENAME}} help

  test-all:
    cmds:
      - go test -tags=all ./...
  
  test-integration:
    cmds:
      - go test --tags=integration ./...


# UTILITY
  loc:
    cmds:
      - cloc . --exclude-dir=.git,temp
